services:
  api-rest:
    image: miguelcarax/api-rest:0.1.0
    build: api-rest
    container_name: api-rest
    networks:
      - internal
      - external
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_API_USER
      - POSTGRES_API_PASSWORD
      - POSTGRES_API_SCHEMA

  postgres:
    image: miguelcarax/postgres:13.1
    build: postgres
    container_name: postgres
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_API_USER
      - POSTGRES_API_PASSWORD
      - POSTGRES_API_SCHEMA

  api-cache:
    image: miguelcarax/api-cache:0.1.0
    build: api-cache
    container_name: api-cache
    ports:
      - "8080:8080"
    depends_on:
      - api-rest
      - redis
    networks:
      - external
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - BACKEND_HOST
      - BACKEND_PORT

  redis:
    image: redis:6
    volumes:
    - redis-data:/data
    networks:
      - external


volumes:
  postgres-data:
  redis-data:

networks:
  internal:
  external:
