apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-rest
  name: api-rest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-rest
  strategy: {}
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
      - image: miguelcarax/api-rest:0.1.0
        name: api-rest
        envFrom:
        - secretRef:
            name: credentials
        resources: {}
