apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-cache
  name: api-cache
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-cache
  type: NodePort
